sudo: required
services:  
  - docker

before_install:
  - docker build -f Dockerfile.dev -t temp .

script:
  - docker run -e CI=true  temp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:  "us-west-2"
  app:  "docker-react"
  environment_name:  "docker-react"
  bucket_name: "elasticbeanstalk-us-west-2-011673140073"
  bucket_path: "docker-react"
  on:
    branch: master  # only push to EB if the master branch is updated.
